[package]
name = "core-variable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.4"
ckb-types = "0.101"
dashmap = "4.0"
lazy_static = "1.4"
parking_lot = "0.11"
